input {
  file {
    path => "/data/personnes.csv"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    mode => "read"
    exit_after_read => true
  }
}

filter {
  csv {
    columns => [
      "id","name","dateOfBirth","gender","children",
      "[address][city]","[address][country]","[address][countrycode]",
      "[location][lat]","[location][lon]","[address][zipcode]"
    ]
    convert => {
      "children" => "integer"
      "[location][lat]" => "float"
      "[location][lon]" => "float"
    }
    remove_field => ["host", "@version", "@timestamp", "message", "log", "event"]
  }

  if [address][zipcode] {
    mutate { add_field => { "dept" => "%{[address][zipcode]}" } }
    truncate { fields => ["dept"] length_bytes => 2 }
    if [dept] == "97" {
      mutate { replace => { "dept" => "%{[address][zipcode]}" } }
      truncate { fields => ["dept"] length_bytes => 3 }
    }
    mutate { add_field => { "index_suffix" => "-%{dept}" } }
  } else {
    mutate { add_field => { "dept" => "" } }
    mutate { add_field => { "index_suffix" => "" } }
  }

  elasticsearch {
    hosts => ["http://${ES_HOST}:9200"]
    user => "elastic"
    password => "${ES_PASSWORD}"
    query_template => "/pipeline/search-by-geo.json"
    index => "bano%{index_suffix}"
    fields => {
      "location" => "[location]"
      "address"  => "[address]"
    }
    remove_field => ["index_suffix", "dept", "path"]
  }
}

output {
  stdout { codec => rubydebug }
  elasticsearch {
    hosts => ["http://${ES_HOST}:9200"]
    user => "elastic"
    password => "${ES_PASSWORD}"
    index => "personnes"
    document_id => "%{[id]}"
  }
}
